[phases.setup]
nixPkgs = ["python312", "ffmpeg", "libopus"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[start]
cmd = "python -m bot"
