from __future__ import annotations

import json
import secrets
import string
from typing import Any

import aiohttp
import discord
from discord import app_commands
from discord.ext import commands

from bot.core.checks import app_admin
from bot.core.utils import embed


def make_code(length: int = 10) -> str:
    alphabet = string.ascii_uppercase + string.digits
    return "-".join("".join(secrets.choice(alphabet) for _ in range(5)) for _ in range(2))


class RestoreConfirmView(discord.ui.View):
    def __init__(self, cog: "ServerBackup", code: str) -> None:
        super().__init__(timeout=90)
        self.cog = cog
        self.code = code

    async def interaction_check(self, interaction: discord.Interaction) -> bool:
        perms = interaction.user.guild_permissions if isinstance(interaction.user, discord.Member) else None
        if perms and perms.manage_guild:
            return True
        await interaction.response.send_message("You need Manage Server to confirm this restore.", ephemeral=True)
        return False

    @discord.ui.button(label="Confirm Restore", style=discord.ButtonStyle.danger)
    async def confirm_restore(self, interaction: discord.Interaction, _: discord.ui.Button) -> None:
        await interaction.response.defer(ephemeral=True, thinking=True)
        result = await self.cog.perform_restore(interaction, self.code)
        await interaction.followup.send(result, ephemeral=True)

    @discord.ui.button(label="Cancel", style=discord.ButtonStyle.secondary)
    async def cancel(self, interaction: discord.Interaction, _: discord.ui.Button) -> None:
        await interaction.response.edit_message(content="Restore cancelled.", embed=None, view=None)


class ServerBackup(commands.Cog):
    def __init__(self, bot: commands.Bot) -> None:
        self.bot = bot

    backup = app_commands.Group(name="backup", description="Server backup code tools")

    def role_payload(self, role: discord.Role) -> dict[str, Any]:
        return {
            "id": role.id,
            "name": role.name,
            "color": role.color.value,
            "hoist": role.hoist,
            "mentionable": role.mentionable,
            "permissions": role.permissions.value,
            "position": role.position,
        }

    def overwrites_payload(self, channel: discord.abc.GuildChannel) -> list[dict[str, Any]]:
        data = []
        for target, overwrite in channel.overwrites.items():
            allow, deny = overwrite.pair()
            data.append({
                "target_type": "role" if isinstance(target, discord.Role) else "member",
                "target_id": target.id,
                "allow": allow.value,
                "deny": deny.value,
            })
        return data

    async def snapshot(self, guild: discord.Guild) -> dict[str, Any]:
        settings = await self.bot.db.get_settings(guild.id, self.bot.settings.default_prefix)
        return {
            "guild": {"id": guild.id, "name": guild.name, "description": guild.description},
            "settings": {k: v for k, v in settings.items() if k != "prefix"},
            "roles": [self.role_payload(role) for role in sorted(guild.roles, key=lambda r: r.position) if not role.managed and role != guild.default_role],
            "categories": [
                {
                    "id": c.id,
                    "name": c.name,
                    "position": c.position,
                    "overwrites": self.overwrites_payload(c),
                }
                for c in sorted(guild.categories, key=lambda c: c.position)
            ],
            "channels": [
                {
                    "id": ch.id,
                    "type": "text" if isinstance(ch, discord.TextChannel) else "voice" if isinstance(ch, discord.VoiceChannel) else "forum" if isinstance(ch, discord.ForumChannel) else "other",
                    "name": ch.name,
                    "position": ch.position,
                    "category_id": ch.category_id,
                    "topic": getattr(ch, "topic", None),
                    "nsfw": getattr(ch, "nsfw", False),
                    "slowmode_delay": getattr(ch, "slowmode_delay", 0),
                    "bitrate": getattr(ch, "bitrate", None),
                    "user_limit": getattr(ch, "user_limit", None),
                    "overwrites": self.overwrites_payload(ch),
                }
                for ch in sorted(guild.channels, key=lambda c: (c.category.position if c.category else -1, c.position))
                if isinstance(ch, (discord.TextChannel, discord.VoiceChannel, discord.ForumChannel))
            ],
        }

    async def send_code(self, interaction: discord.Interaction, code: str) -> None:
        message = f"Backup code for **{interaction.guild.name}**: `{code}`\nGenerated by {interaction.user} ({interaction.user.id})."
        try:
            await interaction.user.send(message)
        except discord.HTTPException:
            pass
        url = self.bot.settings.backup_webhook_url
        if url:
            async with aiohttp.ClientSession() as session:
                await session.post(url, json={"content": message})

    @backup.command(name="make_code", description="Make a backup code for this server")
    @app_admin()
    async def make_backup_code(self, interaction: discord.Interaction) -> None:
        await interaction.response.defer(ephemeral=True)
        code = make_code()
        snapshot = await self.snapshot(interaction.guild)
        await self.bot.db.execute(
            "INSERT INTO backup_codes(code,guild_id,creator_id,snapshot) VALUES(?,?,?,?)",
            code,
            interaction.guild_id,
            interaction.user.id,
            json.dumps(snapshot),
        )
        await self.send_code(interaction, code)
        await interaction.followup.send(
            "Backup code created. I sent it to your DMs"
            + (" and the configured webhook." if self.bot.settings.backup_webhook_url else ". Add BACKUP_WEBHOOK_URL to .env if you want webhook delivery."),
            ephemeral=True,
        )

    @backup.command(name="restore", description="Restore roles/channels/settings from a backup code")
    @app_admin()
    async def restore(self, interaction: discord.Interaction, code: str) -> None:
        row = await self.bot.db.fetchrow("SELECT snapshot FROM backup_codes WHERE code=? AND used=0", code.upper())
        if row is None:
            await interaction.response.send_message("Backup code not found or already used.", ephemeral=True)
            return
        data = json.loads(row["snapshot"])
        summary = (
            f"This will add up to `{len(data.get('roles', []))}` roles, "
            f"`{len(data.get('categories', []))}` categories, and "
            f"`{len(data.get('channels', []))}` channels.\nPress Confirm Restore to continue."
        )
        await interaction.response.send_message(embed=embed("Confirm Backup Restore", summary), view=RestoreConfirmView(self, code.upper()), ephemeral=True)

    async def perform_restore(self, interaction: discord.Interaction, code: str) -> str:
        row = await self.bot.db.fetchrow("SELECT snapshot FROM backup_codes WHERE code=? AND used=0", code.upper())
        if row is None:
            return "Backup code not found or already used."
        data = json.loads(row["snapshot"])
        role_map: dict[int, discord.Role] = {}
        for role_data in data["roles"]:
            role = await interaction.guild.create_role(
                name=role_data["name"],
                permissions=discord.Permissions(role_data["permissions"]),
                color=discord.Color(role_data["color"]),
                hoist=role_data["hoist"],
                mentionable=role_data["mentionable"],
                reason=f"Backup restore by {interaction.user}",
            )
            role_map[role_data["id"]] = role
        category_map: dict[int, discord.CategoryChannel] = {}
        for category_data in data["categories"]:
            category = await interaction.guild.create_category(category_data["name"], reason=f"Backup restore by {interaction.user}")
            category_map[category_data["id"]] = category
        for channel_data in data["channels"]:
            category = category_map.get(channel_data.get("category_id"))
            if channel_data["type"] == "voice":
                await interaction.guild.create_voice_channel(
                    channel_data["name"],
                    category=category,
                    bitrate=channel_data.get("bitrate") or 64000,
                    user_limit=channel_data.get("user_limit") or 0,
                    reason=f"Backup restore by {interaction.user}",
                )
            elif channel_data["type"] == "forum":
                await interaction.guild.create_forum(channel_data["name"], category=category, reason=f"Backup restore by {interaction.user}")
            else:
                await interaction.guild.create_text_channel(
                    channel_data["name"],
                    category=category,
                    topic=channel_data.get("topic"),
                    slowmode_delay=channel_data.get("slowmode_delay") or 0,
                    nsfw=channel_data.get("nsfw") or False,
                    reason=f"Backup restore by {interaction.user}",
                )
        for key, value in data.get("settings", {}).items():
            await self.bot.db.set_settings_value(interaction.guild_id, key, value, self.bot.settings.default_prefix)
        await self.bot.db.execute("UPDATE backup_codes SET used=1 WHERE code=?", code.upper())
        return "Backup restored. Discord may take a minute to show every channel and role."


async def setup(bot: commands.Bot) -> None:
    await bot.add_cog(ServerBackup(bot))
